image: registry.gitlab.com/attu/cxx

stages:
- test

.template: &debug
  before_script:
  - source ./config/debug.sh

.template: &release
  before_script:
  - source ./config/release.sh

.template: &sanitize
  before_script:
  - source ./config/sanitize.sh

.template: &coverage
  before_script:
  - source ./config/coverage.sh
  after_script:
  - >-
     gcovr
     --branch
     --root=build
     --filter='.*cxx.*'
     --filter='.*src.*'
     --print-summary

.template: &build
  stage: test
  script:
  - ./waf configure --prefix=usr build install --destdir=/

test:debug:
  <<: *debug
  <<: *build

test:release:
  <<: *release
  <<: *build

test:sanitize:
  <<: *sanitize
  <<: *build

test:coverage:
  <<: *coverage
  <<: *build
