image: registry.gitlab.com/attu/cxx

stages:
- build
- test
- post

.template: &debug
  stage: build
  before_script:
  - source ./config/debug.sh

.template: &release
  stage: build
  before_script:
  - source ./config/release.sh

.template: &sanitize
  stage: test
  before_script:
  - source ./config/sanitize.sh

.template: &benchmark
  stage: test
  before_script:
  - source ./config/release.sh
  after_script:
  - ./waf benchmark

.template: &coverage
  stage: post
  before_script:
  - source ./config/coverage.sh
  after_script:
  - >-
     gcovr
     --branch
     --root=build
     --filter='.*cxx.*'
     --filter='.*src.*'
     --print-summary

.template: &build
  script:
  - ./waf configure --prefix=usr build install --destdir=/

test:debug:
  <<: *debug
  <<: *build

test:release:
  <<: *release
  <<: *build

test:sanitize:
  <<: *sanitize
  <<: *build

test:benchmark:
  <<: *benchmark
  <<: *build

test:coverage:
  <<: *coverage
  <<: *build
