services:
  base:
    build:
      context: ./docker
    image: registry.gitlab.com/attu/cxx
  cxx:
    build:
      args:
        GROUP: '1002'
        USER: '1001'
      context: ./docker
      dockerfile: develop
    cap_add:
    - SYS_PTRACE
    command: bash
    container_name: cxx
    tty: true
    user: ${UID:-1001}:${GID:-1002}
    volumes:
    - .:/home/user/cxx:rw
    working_dir: /home/user/cxx
version: '3.4'
