services:
  cxx:
    image: registry.gitlab.com/attu/cxx
    build:
      context: ./docker
    cap_add:
    - SYS_PTRACE
    command: bash
    container_name: cxx
    volumes:
    - .:/cxx:rw
    working_dir: /cxx
    user: ${UID:-1001}:${GID:-1002}
version: '3.4'
